import * as types from 'store/mutations-types';

var getLocalInfo = () => {
    let employee = JSON.parse(localStorage.getItem('employee')) || null;

    employee = {
        id: 1240923656267931,
        userId: 1210924798719426,
        name: '我是商户2057',
        code: '1001',
        phone: '13220572057',
        avatarFileId: '1304473028072605',
        titleId: '1240423677486110',
        openId: null,
        storeIds: '1230823666551625,1240323626310282,1270823666535335,6605136521630174,6605137410376137,6605147683710763,6605206639797852',
        role: 'wechat_business_admin',
        merchant: {
            'id': 1270523646267239,
            'code': '10002',
            'status': 1,
            'name': '商户2057',
            'fullName': '商户2059',
            'contact': '商户2057',
            'phone': '18721527961',
            'address': '123',
            'staffCount': '1-5',
            'organizationCode': '1123',
            'businessLicenseNo': '123123123',
            'businessLicenseFileId': 6604949770622483,
            'logoFileId': 6604852739564620,
            'versionType': 1,
            'functionVersion': 1,
            'checkPassTime': null,
            'description': '',
            'businessScopes': [{
                'id': 4,
                'name': '美睫'
            }],
            'source': null,
            'bankAccountDredge': 1,
            'contactIDCard': '12312312312312',
            'emali': '1231',
            'contactPositiveFileId': 6604947336258376,
            'contactNegativeFieId': 6604947137268875,
            'corporate': '222',
            'corporateIdCard': '333',
            'corporatePositiveFileId': 6604947137268875,
            'corporateNegativeFileId': 6604948115479972,
            'organizationFieId': 6604948115479972,
            'sourceMerchantCode': null,
            'balance': null,
            'rate': 3,
            'applySource': null,
            'applyAddress': null,
            'customerService': null,
            'customerServiceCode': null
        },
        storeList: [{
            'id': 1230823666551625,
            'merchantId': 1270523646267239,
            'organizationId': 1270723666310232,
            'code': 'ST1002',
            'name': '剑涛美容美发',
            'fullName': '上海剑涛美发有限公司',
            'relationType': 1,
            'contact': '王剑涛',
            'phone': '13728888888',
            'organizationCode': '310894992813',
            'businessLicenseNo': '28974321-3',
            'businessLicenseFileId': 1260023616947434,
            'areaCode': '310105',
            'businessAreaCode': '310105S001',
            'subwayStationCode': null,
            'subwayLineCode': null,
            'provinceCode': '31',
            'cityCode': '3101',
            'districtCode': '310105',
            'address': '',
            'status': 1,
            'openTimeStart': '08:00',
            'openTimeEnd': '23:30',
            'appoinmentTimeStart': '09:30',
            'appoinmentTimeEnd': '20:30',
            'description': '',
            'feature': '',
            'salesName': null,
            'appointmentHeaderType': 1,
            'businessScopes': [{
                'id': 2,
                'name': '美发'
            }],
            'longitude': 121.362538,
            'latitude': 31.232402,
            'signDistance': null,
            'logoFileId': null
        }, {
            'id': 1240323626310282,
            'merchantId': 1270523646267239,
            'organizationId': 1270723666310232,
            'code': '1001',
            'name': '听雪楼6',
            'fullName': '听雪楼',
            'relationType': 1,
            'contact': '冯子轩',
            'phone': '15262699832',
            'organizationCode': null,
            'businessLicenseNo': null,
            'businessLicenseFileId': 1200123627500737,
            'areaCode': '310104',
            'businessAreaCode': null,
            'subwayStationCode': null,
            'subwayLineCode': null,
            'provinceCode': '31',
            'cityCode': '3101',
            'districtCode': '310104',
            'address': null,
            'status': 1,
            'openTimeStart': '08:00',
            'openTimeEnd': '30:00',
            'appoinmentTimeStart': '08:30',
            'appoinmentTimeEnd': '25:00',
            'description': null,
            'feature': '',
            'salesName': null,
            'appointmentHeaderType': 1,
            'businessScopes': [{
                'id': 2,
                'name': '美发'
            }, {
                'id': 1,
                'name': '美容'
            }],
            'longitude': null,
            'latitude': null,
            'signDistance': null,
            'logoFileId': null
        }, {
            'id': 1270823666535335,
            'merchantId': 1270523646267239,
            'organizationId': 1270723666310232,
            'code': 'ST0001',
            'name': '剑光美容',
            'fullName': '上海剑光美容连锁有限公司',
            'relationType': 1,
            'contact': '剑光',
            'phone': '18721527961',
            'organizationCode': '310897746330',
            'businessLicenseNo': '281385496-8',
            'businessLicenseFileId': null,
            'areaCode': '310106',
            'businessAreaCode': '310106S002',
            'subwayStationCode': '3101D0720',
            'subwayLineCode': '3101D07',
            'provinceCode': '31',
            'cityCode': '3101',
            'districtCode': '310106',
            'address': '上海市长宁区尚品都汇',
            'status': 1,
            'openTimeStart': '08:00',
            'openTimeEnd': '24:30',
            'appoinmentTimeStart': '08:30',
            'appoinmentTimeEnd': '23:30',
            'description': '',
            'feature': '<p>你看看扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩扩 荆防颗粒多多多多多多多多多多多多多多多多多多多多多多多多多多多多多割发代首多所付多所付多所付付付付付付付付付付付付付付付付付付付付付付付付付付付付付付付付付更换幅度过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过过 花儿喜欢灿烂的阳光；鱼儿喜欢清澈的池水；东少d陈子豪昨天晚上，我正在玩电脑，我突然感觉鼻子有点</p><p><br></p><p><br></p>',
            'salesName': null,
            'appointmentHeaderType': null,
            'businessScopes': [{
                'id': 2,
                'name': '美发'
            }, {
                'id': 1,
                'name': '美容'
            }],
            'longitude': 121.362538,
            'latitude': 31.232402,
            'signDistance': 400,
            'logoFileId': null
        }, {
            'id': 6605136521630174,
            'merchantId': 1270523646267239,
            'organizationId': 1270723666310232,
            'code': '1007',
            'name': '全职',
            'fullName': '全职高手',
            'relationType': 1,
            'contact': '牛鹏',
            'phone': '18001909418',
            'organizationCode': null,
            'businessLicenseNo': null,
            'businessLicenseFileId': null,
            'areaCode': null,
            'businessAreaCode': null,
            'subwayStationCode': null,
            'subwayLineCode': null,
            'provinceCode': null,
            'cityCode': null,
            'districtCode': null,
            'address': null,
            'status': 1,
            'openTimeStart': null,
            'openTimeEnd': null,
            'appoinmentTimeStart': null,
            'appoinmentTimeEnd': null,
            'description': null,
            'feature': null,
            'salesName': null,
            'appointmentHeaderType': null,
            'businessScopes': [],
            'longitude': null,
            'latitude': null,
            'signDistance': null,
            'logoFileId': null
        }, {
            'id': 6605137410376137,
            'merchantId': 1270523646267239,
            'organizationId': 1270723666310232,
            'code': '1008',
            'name': '复制门店测试',
            'fullName': 'ytt',
            'relationType': 1,
            'contact': '猫仔',
            'phone': '18721527961',
            'organizationCode': null,
            'businessLicenseNo': null,
            'businessLicenseFileId': null,
            'areaCode': null,
            'businessAreaCode': null,
            'subwayStationCode': null,
            'subwayLineCode': null,
            'provinceCode': null,
            'cityCode': null,
            'districtCode': null,
            'address': null,
            'status': 2,
            'openTimeStart': null,
            'openTimeEnd': null,
            'appoinmentTimeStart': null,
            'appoinmentTimeEnd': null,
            'description': null,
            'feature': null,
            'salesName': null,
            'appointmentHeaderType': null,
            'businessScopes': [],
            'longitude': null,
            'latitude': null,
            'signDistance': null,
            'logoFileId': null
        }, {
            'id': 6605147683710763,
            'merchantId': 1270523646267239,
            'organizationId': 1270723666310232,
            'code': '1009',
            'name': '测试门店2',
            'fullName': 'ytjytjt',
            'relationType': 1,
            'contact': '15262628272',
            'phone': '15262628272',
            'organizationCode': null,
            'businessLicenseNo': null,
            'businessLicenseFileId': null,
            'areaCode': null,
            'businessAreaCode': null,
            'subwayStationCode': null,
            'subwayLineCode': null,
            'provinceCode': null,
            'cityCode': null,
            'districtCode': null,
            'address': '15262628272',
            'status': 2,
            'openTimeStart': null,
            'openTimeEnd': null,
            'appoinmentTimeStart': null,
            'appoinmentTimeEnd': null,
            'description': null,
            'feature': null,
            'salesName': null,
            'appointmentHeaderType': null,
            'businessScopes': [],
            'longitude': null,
            'latitude': null,
            'signDistance': null,
            'logoFileId': null
        }, {
            'id': 6605206639797852,
            'merchantId': 1270523646267239,
            'organizationId': 1270723666310232,
            'code': '1010',
            'name': '海波测试复制门店',
            'fullName': null,
            'relationType': 1,
            'contact': '嵇海波',
            'phone': '18721527961',
            'organizationCode': null,
            'businessLicenseNo': null,
            'businessLicenseFileId': null,
            'areaCode': null,
            'businessAreaCode': null,
            'subwayStationCode': null,
            'subwayLineCode': null,
            'provinceCode': null,
            'cityCode': null,
            'districtCode': null,
            'address': '通协路',
            'status': 1,
            'openTimeStart': null,
            'openTimeEnd': null,
            'appoinmentTimeStart': null,
            'appoinmentTimeEnd': null,
            'description': null,
            'feature': null,
            'salesName': null,
            'appointmentHeaderType': null,
            'businessScopes': [],
            'longitude': null,
            'latitude': null,
            'signDistance': null,
            'logoFileId': null
        }],
        organization: {
            'id': 1270723666310232,
            'order': 1,
            'parentId': null,
            'parentIds': ',',
            'oldParentId': null,
            'oldParentIds': null,
            'level': 1,
            'leaf': true,
            'name': '总部',
            'merchantId': 1270523646267239,
            'parent': null
        },
        merchantRole: {},
        skills: []
    };

    var data = {
        user: {},
        merchant: {},
        storeList: [],
        organization: {},
        merchantRole: {},
        skills: [],
        store: {}
    };
    if (employee) {
        data.user = {
            id: employee.id,
            userId: employee.userId,
            name: employee.name,
            code: employee.code,
            phone: employee.phone,
            avatarFileId: employee.avatarFileId,
            titleId: employee.titleId,
            openId: employee.openId,
            storeIds: employee.storeIds,
            role: employee.role
        };
        data.merchant = employee.merchant;
        data.storeList = employee.storeList;
        data.organization = employee.organization;
        data.merchantRole = employee.merchantRole;
        data.skills = employee.skills;
        if (employee.store && employee.store.id) {
            data.store = employee.store;
            if (!employee.storeList.length) {
                employee.storeList.push(employee.store);
            }
        } else if (employee.storeList.length) {
            data.store = employee.storeList[0];
        }
    }
    return data;
};

export default {
    [types.UPDATE_LOCAL](state) {
        Object.assign(state, getLocalInfo());
    }
};
